---
- hosts: localhost
  remote_user: no
  sudo: no
  tasks:

  - name: Install wget for next steps
    yum: pkg=wget state=present 

  - name: Install git client if not present (yum)
    yum: pkg=git state=present

  - name: Install java client if not present (yum)
    yum: name=java state=present

  - name: Install docker if not present (standard method)
    shell: "wget -qO- https://get.docker.com/ | sh"

  - name: Install docker-compose if not present (standard method)
    shell: "curl -L https://github.com/docker/compose/releases/download/1.5.2/docker-compose-`uname -s`-`uname -m` > /usr/bin/docker-compose"

  - name: Make docker-compose executable
    file: name=/usr/bin/docker-compose mode="a+x"

  - name: Activate and start docker service
    service: name=docker state=started enabled=yes

  - name: Patch the docker issue https://github.com/docker/docker/issues/17653
    lineinfile: dest=/usr/lib/systemd/system/docker.service state=present regexp=^ExecStart= line="ExecStart=/usr/bin/docker daemon --exec-opt native.cgroupdriver=cgroupfs -H fd://"

  - name : Create the almbox  user
    user: name=almbox groups="docker" password=$6$W7ZiPYhU$We1NsDUTeYLe3NR/o7u.XScPIt.l8zYWLnpuBc1CddTuL0tXjItjajOAypSuNqA70IMMAgLvi/WB23b.j.WgK1

  - name: Create docker volume /volumes/sonar/data
    file: path=/volumes/sonar/data state=directory owner=1000 group=1000

  - name: Create docker volume /volumes/sonar/extensions
    file: path=/volumes/sonar/extensions state=directory owner=1000 group=1000

  - name: Create docker volume /volumes/jenkins
    file: path=/volumes/jenkins state=directory owner=1000 group=1000

  - name: Create docker volume /volumes/nexus
    file: path=/volumes/nexus state=directory owner=200 group=200

  - name: Create docker volume /volumes/elk
    file: path=/volumes/elk state=directory owner=103 group=107

  - name: Copy dockercmds.h in /etc/profile.d
    copy: src=dockercmds.sh dest=/etc/profile.d/ mode="a+x"

  - name: Create docker volume /volumes/mesos-master_1-logs
    file: path=/volumes/mesos-master_1-logs state=directory owner=1 group=1

  - name: Create docker volume /volumes/mesos-slave_1-logs
    file: path=/volumes/logs/mesos-slave_1-logs state=directory owner=1 group=1

  # POSTPONED
  #- name: Allow docker network routing
  #  iptables: chain=DOCKER protocol=tcp jump=ACCEPT
